name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # Only run on non-forked PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Danger
        run: yarn global add danger
      - name: Validate PR title validation rules
        working-directory: ./ci/validate-pr-title
        run: node validate.test.js
      - name: Run Danger
        run: danger ci
        working-directory: ./ci/validate-pr-title
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}



#The changes I made are:

#In the actions/checkout step, I updated the action to v2.
#In the actions/setup-node step, I quoted the node version string to ensure it is interpreted as a string and not a number.
#In the install danger step, I updated the command to be more explicit and added a capital letter for consistency.
#In the Run Danger step, I updated the name to be more descriptive and added a capital letter for consistency.
